import bcrypt from "bcryptjs";
import { nanoid } from "nanoid";
import type {
  DatabaseShape,
  Opportunity,
  OpportunityType,
  Source,
  User,
} from "./types";
import { computeScore } from "./utils/scoring";

/**
 * ─── Seed data ───────────────────────────────────────────────────
 * Deterministic demo content so every fresh install looks alive:
 *  • 3 users (1 admin + 2 members, passwords documented in README)
 *  • 6 scan sources
 *  • 28 opportunities spanning all 6 types
 *
 * Scores are computed with the real `computeScore()` so seed data
 * exercises the same path as user-submitted listings.
 */

const DAY = 86_400_000;
const now = Date.now();
const daysAgo = (d: number) => new Date(now - d * DAY).toISOString();
const daysFromNow = (d: number) => new Date(now + d * DAY).toISOString();

interface SeedOpp {
  title: string;
  organization: string;
  type: OpportunityType;
  category: string;
  description: string;
  location: string;
  remote: boolean;
  amountMin?: number;
  amountMax?: number;
  currency?: string;
  deadlineInDays?: number | null;
  url: string;
  source: string;
  tags: string[];
  featured?: boolean;
  applicantsCount: number;
  views: number;
  ageDays: number;
}

const OPPS: SeedOpp[] = [
  {
    title: "Senior Full-Stack Engineer (React + Node)",
    organization: "Northwind Labs",
    type: "Job",
    category: "Engineering",
    description:
      "Northwind Labs is hiring a senior full-stack engineer to own our analytics dashboard end to end. You'll work with React, TypeScript, Node and Postgres across a small senior team. We value clean APIs, thoughtful code review, and engineers who talk to customers. Fully remote with quarterly on-sites, equity, and a learning budget.",
    location: "Remote",
    remote: true,
    amountMin: 120000,
    amountMax: 165000,
    currency: "USD",
    deadlineInDays: 21,
    url: "https://example.com/jobs/northwind-senior-fullstack",
    source: "Remote Jobs Board",
    tags: ["react", "node", "typescript", "postgres", "remote"],
    featured: true,
    applicantsCount: 84,
    views: 2310,
    ageDays: 2,
  },
  {
    title: "Climate Adaptation Innovation Grant 2026",
    organization: "Green Futures Foundation",
    type: "Grant",
    category: "Climate",
    description:
      "Non-dilutive grants of up to $250,000 for early-stage teams building climate adaptation technology for vulnerable regions. Priority areas: water security, heat resilience, and smallholder agriculture. Two-stage application: 2-page concept note, then full proposal for shortlisted teams. Winners also join a 6-month support cohort.",
    location: "Worldwide",
    remote: true,
    amountMin: 50000,
    amountMax: 250000,
    currency: "USD",
    deadlineInDays: 45,
    url: "https://example.com/grants/climate-adaptation-2026",
    source: "Green Grants DB",
    tags: ["climate", "grant", "non-dilutive", "agritech", "water"],
    featured: true,
    applicantsCount: 312,
    views: 8940,
    ageDays: 5,
  },
  {
    title: "City Metro E-Ticketing System — RFP",
    organization: "Metro Transit Authority",
    type: "Tender",
    category: "GovTech",
    description:
      "Open tender for design, supply and maintenance of a contactless e-ticketing system across 4 metro lines (62 stations). Scope includes gates, validators, mobile SDK and a 5-year maintenance contract. Bidders must show 2 comparable deployments. Pre-bid conference is mandatory; documents available on the portal.",
    location: "Lagos, Nigeria",
    remote: false,
    amountMin: 2000000,
    amountMax: 4500000,
    currency: "USD",
    deadlineInDays: 30,
    url: "https://example.com/tenders/metro-eticketing",
    source: "Public Tenders Portal",
    tags: ["tender", "govtech", "infrastructure", "rfp"],
    featured: true,
    applicantsCount: 18,
    views: 1420,
    ageDays: 7,
  },
  {
    title: "Brand Identity for Fintech Launch",
    organization: "Paynest",
    type: "Freelance",
    category: "Design",
    description:
      "Seed-stage fintech needs a complete brand identity: logo system, colour + type guidelines, pitch-deck template and marketing site art direction. 4–6 week engagement, async-friendly, two structured feedback rounds per deliverable. Portfolio with at least one fintech or SaaS rebrand required.",
    location: "Remote",
    remote: true,
    amountMin: 4000,
    amountMax: 8000,
    currency: "USD",
    deadlineInDays: 14,
    url: "https://example.com/freelance/paynest-brand",
    source: "Freelance Hub",
    tags: ["branding", "logo", "fintech", "contract"],
    applicantsCount: 47,
    views: 980,
    ageDays: 1,
  },
  {
    title: "Pre-Seed Round — Developer Tools",
    organization: "BluePeak Ventures",
    type: "Funding",
    category: "DevTools",
    description:
      "BluePeak is leading pre-seed rounds ($300k–$750k) for developer-tools startups with early revenue or 500+ active users. Thesis: AI-assisted testing, local-first collaboration, and boring infrastructure that just works. Rolling applications with a 2-week decision SLA after first call. Warm intros welcome but not required.",
    location: "San Francisco, USA",
    remote: false,
    amountMin: 300000,
    amountMax: 750000,
    currency: "USD",
    deadlineInDays: null,
    url: "https://example.com/funding/bluepeak-preseed",
    source: "VC Tracker",
    tags: ["pre-seed", "devtools", "saas", "venture"],
    featured: true,
    applicantsCount: 129,
    views: 5120,
    ageDays: 9,
  },
  {
    title: "African Data Science Scholarship 2026",
    organization: "Open Learning Collective",
    type: "Scholarship",
    category: "Education",
    description:
      "Full-tuition scholarships for a 9-month applied data-science program, open to residents of 12 African countries. Covers tuition, laptop stipend and mentorship from industry practitioners. No prior degree required — selection is by aptitude test and motivation statement. 200 seats across 3 cohorts.",
    location: "Hybrid — Nairobi & Remote",
    remote: true,
    amountMin: 3500,
    amountMax: 3500,
    currency: "USD",
    deadlineInDays: 28,
    url: "https://example.com/scholarships/ads-2026",
    source: "Scholarships Wire",
    tags: ["scholarship", "data-science", "africa", "education"],
    applicantsCount: 1840,
    views: 22100,
    ageDays: 12,
  },
  {
    title: "ML Engineer — Document Understanding",
    organization: "Paperless Inc.",
    type: "Job",
    category: "AI/ML",
    description:
      "Own fine-tuning and evaluation of vision-language models that extract structured data from invoices and contracts. Stack: PyTorch, HuggingFace, Modal, Weights & Biases. You'll ship to production weekly and publish eval reports internally. Hybrid role in Toronto with relocation support.",
    location: "Toronto, Canada",
    remote: false,
    amountMin: 140000,
    amountMax: 185000,
    currency: "CAD",
    deadlineInDays: 18,
    url: "https://example.com/jobs/paperless-ml",
    source: "Remote Jobs Board",
    tags: ["ml", "pytorch", "nlp", "hybrid"],
    applicantsCount: 61,
    views: 1870,
    ageDays: 3,
  },
  {
    title: "Open Source Sustainability Grant",
    organization: "Code Commons Fund",
    type: "Grant",
    category: "Open Source",
    description:
      "$10k–$60k grants for maintainers of widely-used open source projects to fund focused maintenance sprints: security audits, documentation overhauls, or long-delayed refactors. Monthly rolling deadline, lightweight application (one page + repo link). Decisions within 3 weeks.",
    location: "Worldwide",
    remote: true,
    amountMin: 10000,
    amountMax: 60000,
    currency: "USD",
    deadlineInDays: 9,
    url: "https://example.com/grants/code-commons",
    source: "Green Grants DB",
    tags: ["open-source", "grant", "maintainers", "security"],
    applicantsCount: 203,
    views: 6640,
    ageDays: 4,
  },
  {
    title: "National Health Records Digitisation — Phase 2",
    organization: "Ministry of Health",
    type: "Tender",
    category: "HealthTech",
    description:
      "Restricted tender for phase 2 of the national health-records digitisation program: FHIR integration layer, facility onboarding for 300 clinics, and training. Open to vendors pre-qualified in phase 1 plus new bidders meeting the technical threshold (see annex B). 18-month delivery with milestone payments.",
    location: "Accra, Ghana",
    remote: false,
    amountMin: 800000,
    amountMax: 1500000,
    currency: "USD",
    deadlineInDays: 35,
    url: "https://example.com/tenders/health-records-p2",
    source: "Public Tenders Portal",
    tags: ["tender", "healthtech", "fhir", "government"],
    applicantsCount: 11,
    views: 760,
    ageDays: 6,
  },
  {
    title: "Next.js Performance Audit (Contract)",
    organization: "Shopline",
    type: "Freelance",
    category: "Engineering",
    description:
      "2-week contract to audit and fix Core Web Vitals on a high-traffic Next.js storefront (2M monthly sessions). Deliverables: Lighthouse/Lab + field-data report, prioritized fix list, and implementation of top fixes with before/after measurements. Must have public case studies of similar audits.",
    location: "Remote",
    remote: true,
    amountMin: 3000,
    amountMax: 6000,
    currency: "USD",
    deadlineInDays: 7,
    url: "https://example.com/freelance/shopline-perf",
    source: "Freelance Hub",
    tags: ["nextjs", "performance", "contract", "ecommerce"],
    applicantsCount: 29,
    views: 640,
    ageDays: 2,
  },
  {
    title: "Angel Cheques for Solo Founders",
    organization: "Solo Capital",
    type: "Funding",
    category: "Generalist",
    description:
      "$50k–$150k first cheques for solo technical founders, decided in 7 days on a 10-slide deck plus product demo. No lead required, SAFE with MFN. We have backed 40+ solo founders since 2021 and run a weekly builders' call. Rolling — apply any time.",
    location: "Remote-first",
    remote: true,
    amountMin: 50000,
    amountMax: 150000,
    currency: "USD",
    deadlineInDays: null,
    url: "https://example.com/funding/solo-capital",
    source: "VC Tracker",
    tags: ["angel", "solo-founder", "safe", "rolling"],
    applicantsCount: 410,
    views: 11200,
    ageDays: 15,
  },
  {
    title: "Women in STEM Masters Scholarship",
    organization: "Meridian Trust",
    type: "Scholarship",
    category: "Education",
    description:
      "Covers full tuition plus living stipend for women pursuing STEM masters degrees at 8 partner universities across the UK and Canada. 40 awards per year. Requires admission offer (conditional accepted) and two references. Renewal for year 2 is automatic with satisfactory progress.",
    location: "UK & Canada",
    remote: false,
    amountMin: 25000,
    amountMax: 45000,
    currency: "GBP",
    deadlineInDays: 52,
    url: "https://example.com/scholarships/meridian-stem",
    source: "Scholarships Wire",
    tags: ["scholarship", "stem", "masters", "women-in-tech"],
    applicantsCount: 960,
    views: 15800,
    ageDays: 10,
  },
  {
    title: "Product Designer — Mobile Banking",
    organization: "Kuda-style case study: OrbitPay",
    type: "Job",
    category: "Design",
    description:
      "OrbitPay is rebuilding its consumer banking app and needs a product designer to lead the savings and budgeting flows. You'll run discovery with 2M+ users' data, prototype in Figma, and pair with engineers through release. 3+ years in fintech or consumer mobile preferred.",
    location: "London, UK (Hybrid)",
    remote: false,
    amountMin: 65000,
    amountMax: 90000,
    currency: "GBP",
    deadlineInDays: 16,
    url: "https://example.com/jobs/orbitpay-designer",
    source: "Remote Jobs Board",
    tags: ["product-design", "fintech", "figma", "mobile"],
    applicantsCount: 143,
    views: 3210,
    ageDays: 4,
  },
  {
    title: "Small Business Digitalisation Voucher",
    organization: "City Enterprise Office",
    type: "Grant",
    category: "SME",
    description:
      "Vouchers worth up to €5,000 covering 80% of approved digitalisation costs (webshop setup, POS systems, bookkeeping software) for businesses under 10 employees registered before 2024. Simple online form, approval in 10 working days, 300 vouchers available this quarter.",
    location: "Berlin, Germany",
    remote: false,
    amountMin: 1000,
    amountMax: 5000,
    currency: "EUR",
    deadlineInDays: 60,
    url: "https://example.com/grants/digitalisation-voucher",
    source: "Green Grants DB",
    tags: ["sme", "voucher", "digitalisation", "grant"],
    applicantsCount: 88,
    views: 1340,
    ageDays: 8,
  },
  {
    title: "Solar Mini-Grids for 50 Villages — EPC",
    organization: "Rural Energy Agency",
    type: "Tender",
    category: "Energy",
    description:
      "Engineering, procurement and construction of solar mini-grids (20–100 kW each) for 50 villages, including 3 years of O&M. Lots may be bid individually or bundled. Bidders need mini-grid experience in Sub-Saharan Africa and local-content commitments per section 4 of the RFP.",
    location: "Abuja, Nigeria",
    remote: false,
    amountMin: 5000000,
    amountMax: 9000000,
    currency: "USD",
    deadlineInDays: 42,
    url: "https://example.com/tenders/solar-minigrids",
    source: "Public Tenders Portal",
    tags: ["tender", "solar", "energy", "epc"],
    featured: true,
    applicantsCount: 9,
    views: 1120,
    ageDays: 11,
  },
  {
    title: "Technical Writer — API Docs Sprint",
    organization: "Hexagate",
    type: "Freelance",
    category: "Writing",
    description:
      "6-week docs sprint: rewrite REST + webhook reference for a security API, add runnable examples in 4 languages, and set up docs-as-code checks in CI. You'll work directly with the founding engineer. Rate is weekly; docs portfolio with API samples required.",
    location: "Remote",
    remote: true,
    amountMin: 2500,
    amountMax: 5000,
    currency: "USD",
    deadlineInDays: 11,
    url: "https://example.com/freelance/hexagate-docs",
    source: "Freelance Hub",
    tags: ["technical-writing", "api", "docs", "contract"],
    applicantsCount: 36,
    views: 720,
    ageDays: 3,
  },
  {
    title: "Seed Round — Vertical SaaS for Clinics",
    organization: "Harbor Health Ventures",
    type: "Funding",
    category: "HealthTech",
    description:
      "Leading $1M–$2.5M seed rounds for vertical SaaS serving outpatient clinics: scheduling, billing and patient comms in one suite. Looking for teams with a clinical co-founder and $15k+ MRR. We lead, help recruit, and open doors to 200+ clinic groups in our network.",
    location: "Boston, USA",
    remote: false,
    amountMin: 1000000,
    amountMax: 2500000,
    currency: "USD",
    deadlineInDays: null,
    url: "https://example.com/funding/harbor-seed",
    source: "VC Tracker",
    tags: ["seed", "healthtech", "saas", "b2b"],
    applicantsCount: 57,
    views: 2890,
    ageDays: 13,
  },
  {
    title: "Global UI/UX Design Fellowship",
    organization: "DesignForward",
    type: "Scholarship",
    category: "Design",
    description:
      "12-week remote fellowship pairing 50 emerging designers with mentors from top product companies. Weekly critiques, real client briefs, and a demo-day portfolio review. $1,500 stipend plus Figma + course licences. Open worldwide; English working proficiency required.",
    location: "Remote",
    remote: true,
    amountMin: 1500,
    amountMax: 1500,
    currency: "USD",
    deadlineInDays: 19,
    url: "https://example.com/scholarships/designforward",
    source: "Scholarships Wire",
    tags: ["fellowship", "design", "mentorship", "remote"],
    applicantsCount: 2210,
    views: 18400,
    ageDays: 6,
  },
  {
    title: "DevOps Engineer — Platform Team",
    organization: "Cirrus Cloud",
    type: "Job",
    category: "Engineering",
    description:
      "Platform team of 6 supporting 80 engineers. Own Kubernetes clusters (EKS), Terraform modules and the internal developer portal. We deploy 50× a day with progressive delivery and invest heavily in golden paths. On-call is compensated and genuinely sustainable (1 week in 8).",
    location: "Remote (EU timezones)",
    remote: true,
    amountMin: 95000,
    amountMax: 130000,
    currency: "EUR",
    deadlineInDays: 25,
    url: "https://example.com/jobs/cirrus-devops",
    source: "Remote Jobs Board",
    tags: ["devops", "kubernetes", "terraform", "platform"],
    applicantsCount: 73,
    views: 2140,
    ageDays: 5,
  },
  {
    title: "Artist Residency + Production Grant",
    organization: "Kiln House Arts",
    type: "Grant",
    category: "Arts",
    description:
      "3-month residency with studio, accommodation and a $12,000 production budget for ceramic and mixed-media artists. Ends with a group show and catalogue feature. Open internationally; travel stipend available for artists from the Global South. 6 residents per cycle.",
    location: "Lisbon, Portugal",
    remote: false,
    amountMin: 12000,
    amountMax: 12000,
    currency: "USD",
    deadlineInDays: 33,
    url: "https://example.com/grants/kiln-residency",
    source: "Green Grants DB",
    tags: ["arts", "residency", "grant", "ceramics"],
    applicantsCount: 190,
    views: 4230,
    ageDays: 9,
  },
  {
    title: "Highway Maintenance Framework (3 Lots)",
    organization: "Roads Authority",
    type: "Tender",
    category: "Infrastructure",
    description:
      "4-year framework for routine and emergency highway maintenance across 3 lots (north/central/south corridors). Covers resurfacing, drainage, signage and winter response. Framework value €40M–€60M total. ISO 9001 + 14001 required; site visits scheduled weekly in October.",
    location: "Madrid, Spain",
    remote: false,
    amountMin: 40000000,
    amountMax: 60000000,
    currency: "EUR",
    deadlineInDays: 48,
    url: "https://example.com/tenders/highway-framework",
    source: "Public Tenders Portal",
    tags: ["tender", "infrastructure", "roads", "framework"],
    applicantsCount: 7,
    views: 540,
    ageDays: 14,
  },
  {
    title: "Motion Designer — Product Launch Video",
    organization: "Loopwork",
    type: "Freelance",
    category: "Design",
    description:
      "90-second launch video for a project-management tool: storyboard, animation and sound direction. Style references provided; you bring the motion craft (After Effects + Rive a plus). Fixed price, 3-week timeline, credit + testimonial. Two similar launch videos in portfolio required.",
    location: "Remote",
    remote: true,
    amountMin: 3500,
    amountMax: 5500,
    currency: "USD",
    deadlineInDays: 6,
    url: "https://example.com/freelance/loopwork-motion",
    source: "Freelance Hub",
    tags: ["motion", "video", "animation", "contract"],
    applicantsCount: 52,
    views: 890,
    ageDays: 1,
  },
  {
    title: "Climate Fintech Accelerator — Cohort 5",
    organization: "Terra Accelerate",
    type: "Funding",
    category: "Climate",
    description:
      "$200k investment + 12-week program for startups at the intersection of climate and fintech: carbon accounting, green lending, MRV tooling. Backed by 3 tier-1 VCs with demo day to 400+ investors. 8% acceptance rate last cohort; rolling interviews until spots fill.",
    location: "Amsterdam, Netherlands",
    remote: false,
    amountMin: 200000,
    amountMax: 200000,
    currency: "EUR",
    deadlineInDays: 23,
    url: "https://example.com/funding/terra-cohort5",
    source: "VC Tracker",
    tags: ["accelerator", "climate", "fintech", "seed"],
    featured: true,
    applicantsCount: 480,
    views: 12600,
    ageDays: 7,
  },
  {
    title: "Chevening-style Tech Policy Fellowship",
    organization: "FutureGov Institute",
    type: "Scholarship",
    category: "Policy",
    description:
      "9-month paid fellowship placing technologists inside government digital-service teams across 4 countries. Includes policy training at Oxford, executive coaching, and a $45k stipend. Ideal for engineers and designers with 3+ years experience curious about public-interest technology.",
    location: "Multiple countries",
    remote: false,
    amountMin: 45000,
    amountMax: 45000,
    currency: "USD",
    deadlineInDays: 39,
    url: "https://example.com/scholarships/futuregov",
    source: "Scholarships Wire",
    tags: ["fellowship", "policy", "govtech", "paid"],
    applicantsCount: 640,
    views: 9310,
    ageDays: 16,
  },
  {
    title: "Customer Success Manager (SaaS)",
    organization: "Helpwise",
    type: "Job",
    category: "Customer Success",
    description:
      "Own a book of 60 mid-market accounts for a support-automation SaaS. You run onboarding, QBRs and expansion plays with a clear playbook — and improve the playbook. OTE $95k–$120k with uncapped commission. Remote within US timezones; 2+ years SaaS CS experience needed.",
    location: "Remote (US)",
    remote: true,
    amountMin: 70000,
    amountMax: 90000,
    currency: "USD",
    deadlineInDays: 13,
    url: "https://example.com/jobs/helpwise-csm",
    source: "Remote Jobs Board",
    tags: ["customer-success", "saas", "remote", "b2b"],
    applicantsCount: 112,
    views: 2760,
    ageDays: 4,
  },
  {
    title: "Rural Women Agripreneur Grant",
    organization: "Harvest Trust",
    type: "Grant",
    category: "Agriculture",
    description:
      "$2,000–$10,000 micro-grants plus agronomy training for women-led agribusinesses (processing, storage, market linkage). 500 grants per cycle across Kenya, Ghana and Rwanda. Application by mobile form or USSD in English, Swahili, Twi and Kinyarwanda. No collateral or fees.",
    location: "Kenya, Ghana, Rwanda",
    remote: false,
    amountMin: 2000,
    amountMax: 10000,
    currency: "USD",
    deadlineInDays: 31,
    url: "https://example.com/grants/harvest-agripreneur",
    source: "Green Grants DB",
    tags: ["grant", "agriculture", "women", "micro-grant"],
    applicantsCount: 3120,
    views: 28700,
    ageDays: 18,
  },
  {
    title: "School Laptop Supply — 20,000 Units",
    organization: "Education Procurement Unit",
    type: "Tender",
    category: "Education",
    description:
      "Supply and 3-year warranty of 20,000 ruggedised student laptops (spec in annex A), plus imaging, delivery to 12 depots and teacher train-the-trainer for 400 staff. Split award possible (max 2 vendors). Samples required with bid; late samples disqualify.",
    location: "Nairobi, Kenya",
    remote: false,
    amountMin: 6000000,
    amountMax: 8000000,
    currency: "USD",
    deadlineInDays: 27,
    url: "https://example.com/tenders/school-laptops",
    source: "Public Tenders Portal",
    tags: ["tender", "edtech", "procurement", "hardware"],
    applicantsCount: 14,
    views: 980,
    ageDays: 5,
  },
  {
    title: "Smart Contract Audit (DeFi Lending)",
    organization: "Vault Protocol",
    type: "Freelance",
    category: "Security",
    description:
      "Independent audit of ~3,500 lines of Solidity (lending pools + liquidation engine) before mainnet. Deliverable: findings report with severity ratings, PoCs for criticals, and a fix-review round. Public audit history required; cantina/code4rena leaderboard presence strongly preferred.",
    location: "Remote",
    remote: true,
    amountMin: 15000,
    amountMax: 30000,
    currency: "USD",
    deadlineInDays: 10,
    url: "https://example.com/freelance/vault-audit",
    source: "Freelance Hub",
    tags: ["solidity", "audit", "defi", "security"],
    featured: true,
    applicantsCount: 21,
    views: 1530,
    ageDays: 2,
  },
];

const SOURCES: Array<Omit<Source, "id" | "lastScanAt" | "foundCount">> = [
  {
    name: "Remote Jobs Board",
    kind: "Job",
    url: "https://example.com/sources/remote-jobs",
    status: "active",
  },
  {
    name: "Green Grants DB",
    kind: "Grant",
    url: "https://example.com/sources/green-grants",
    status: "active",
  },
  {
    name: "Public Tenders Portal",
    kind: "Tender",
    url: "https://example.com/sources/tenders",
    status: "active",
  },
  {
    name: "Freelance Hub",
    kind: "Freelance",
    url: "https://example.com/sources/freelance",
    status: "active",
  },
  {
    name: "VC Tracker",
    kind: "Funding",
    url: "https://example.com/sources/vc",
    status: "active",
  },
  {
    name: "Scholarships Wire",
    kind: "Mixed",
    url: "https://example.com/sources/scholarships",
    status: "paused",
  },
];

function statusFor(deadlineInDays?: number | null): Opportunity["status"] {
  if (deadlineInDays == null) return "open";
  if (deadlineInDays <= 7) return "closing-soon";
  return "open";
}

export function seedDatabase(): DatabaseShape {
  const adminPassword = bcrypt.hashSync("admin123", 8);
  const demoPassword = bcrypt.hashSync("demo1234", 8);

  const admin: User = {
    id: "user-admin-001",
    name: "Ada Admin",
    email: "admin@oppscan.io",
    passwordHash: adminPassword,
    role: "admin",
    avatarColor: "#7c3aed",
    createdAt: daysAgo(90),
  };
  const demo: User = {
    id: "user-demo-001",
    name: "Demo User",
    email: "demo@oppscan.io",
    passwordHash: demoPassword,
    role: "user",
    avatarColor: "#0ea5e9",
    createdAt: daysAgo(30),
  };
  const member: User = {
    id: "user-member-001",
    name: "Maya Scout",
    email: "maya@example.com",
    passwordHash: demoPassword,
    role: "user",
    avatarColor: "#f59e0b",
    createdAt: daysAgo(12),
  };

  const opportunities: Opportunity[] = OPPS.map((s, i) => {
    const createdAt = daysAgo(s.ageDays);
    const base = {
      id: `opp-${String(i + 1).padStart(3, "0")}-${nanoid(6)}`,
      title: s.title,
      organization: s.organization,
      type: s.type,
      category: s.category,
      description: s.description,
      location: s.location,
      remote: s.remote,
      amountMin: s.amountMin ?? null,
      amountMax: s.amountMax ?? null,
      currency: s.currency ?? null,
      deadline:
        s.deadlineInDays == null ? null : daysFromNow(s.deadlineInDays),
      url: s.url,
      source: s.source,
      tags: s.tags,
      status: statusFor(s.deadlineInDays),
      featured: s.featured ?? false,
      applicantsCount: s.applicantsCount,
      views: s.views,
      score: 0, // computed below
      postedBy: null,
      createdAt,
      updatedAt: createdAt,
    };
    return { ...base, score: computeScore(base) };
  });

  const sources: Source[] = SOURCES.map((s) => ({
    ...s,
    id: `src-${nanoid(8)}`,
    lastScanAt: daysAgo(1),
    foundCount: opportunities.filter((o) => o.source === s.name).length,
  }));

  return {
    version: 1,
    users: [admin, demo, member],
    opportunities,
    saved: [
      {
        userId: demo.id,
        opportunityId: opportunities[1].id,
        createdAt: daysAgo(2),
      },
      {
        userId: demo.id,
        opportunityId: opportunities[4].id,
        createdAt: daysAgo(1),
      },
    ],
    sources,
    scans: [
      {
        id: `scan-${nanoid(8)}`,
        startedAt: daysAgo(1),
        finishedAt: daysAgo(1),
        sourcesScanned: 5,
        newFound: opportunities.length,
        newIds: [],
        status: "completed",
      },
    ],
  };
}
